(function () {
  "use strict";

  const exact = {
    "normal histology": "Mô học bình thường",
    "normal thyroid": "Tuyến giáp bình thường",
    "benign proliferative lesions": "Tổn thương tăng sinh lành tính",
    "benign prolif lesions": "Tổn thương tăng sinh lành tính",
    "benign epithelial tumours and precursors": "U biểu mô lành tính và tổn thương tiền thân",
    "malignant epithelial tumours": "U biểu mô ác tính",
    "inflammatory reactive": "Tổn thương viêm và phản ứng",
    "inflammatory disorders": "Bệnh lý viêm",
    "misc non neoplastic lesions": "Các tổn thương không tân sinh khác",
    "rare unusual tumors": "Các u hiếm gặp",
    "rare breast tumors": "Các u vú hiếm gặp",
    "epithelial polyps": "Polyp biểu mô",
    "hamartomatous polyps": "Polyp mô thừa",
    "heterotopic tissues": "Mô lạc chỗ",
    "metastases to stomach": "Di căn đến dạ dày",
    "tumours of the stomach": "U dạ dày",
    "tumours of the lung": "U phổi",
    "tumours of the breast": "U vú",
    "tumours of the thyroid": "U tuyến giáp",
    "stomach": "Dạ dày",
    "oesophagus": "Thực quản",
    "esophagus": "Thực quản",
    "colon": "Đại tràng",
    "rectum": "Trực tràng",
    "appendix": "Ruột thừa",
    "small intestine": "Ruột non",
    "breast": "Vú",
    "lung": "Phổi",
    "thyroid": "Tuyến giáp",
    "pancreas": "Tụy",
    "liver": "Gan",
    "gallbladder": "Túi mật",
    "kidney": "Thận",
    "urinary bladder": "Bàng quang",
    "prostate": "Tuyến tiền liệt",
    "testis": "Tinh hoàn",
    "ovary": "Buồng trứng",
    "uterine cervix": "Cổ tử cung",
    "uterine corpus": "Thân tử cung",
    "endometrium": "Nội mạc tử cung",
    "vagina": "Âm đạo",
    "vulva": "Âm hộ",
    "skin": "Da",
    "soft tissue": "Mô mềm",
    "bone": "Xương",
    "central nervous system": "Hệ thần kinh trung ương",
    "head and neck": "Đầu và cổ",
    "mediastinum": "Trung thất",
    "peritoneum": "Phúc mạc",
    "blunt duct adenosis": "Bệnh tuyến ống tận cùn",
    "ductal hyperplasia": "Quá sản ống tuyến",
    "atypical ductal hyperplasia": "Quá sản ống tuyến không điển hình",
    "lobular hyperplasia": "Quá sản tiểu thùy",
    "fibrocystic change": "Biến đổi xơ nang",
    "intraductal papilloma": "U nhú nội ống",
    "microglandular adenosis": "Bệnh tuyến vi nang",
    "sclerosing adenosis": "Bệnh tuyến xơ hóa",
    "radial scar": "Sẹo tỏa tia",
    "fat necrosis": "Hoại tử mỡ",
    "granulomatous mastitis": "Viêm vú dạng hạt",
    "lymphocytic mastitis": "Viêm vú lympho bào",
    "plasma cell mastitis": "Viêm vú tương bào",
    "silicone mastitis": "Viêm vú do silicone",
    "ductal carcinoma in situ": "Ung thư biểu mô ống tại chỗ",
    "lobular carcinoma in situ": "Tân sinh tiểu thùy tại chỗ",
    "infiltrating ductal carcinoma": "Ung thư biểu mô ống xâm nhập",
    "invasive ductal carcinoma": "Ung thư biểu mô ống xâm nhập",
    "infiltrating lobular carcinoma": "Ung thư biểu mô tiểu thùy xâm nhập",
    "invasive lobular carcinoma": "Ung thư biểu mô tiểu thùy xâm nhập",
    "mucinous colloid carcinoma": "Ung thư biểu mô dạng nhầy",
    "paget disease of breast": "Bệnh Paget vú",
    "fibroadenoma": "U xơ tuyến",
    "phyllodes tumor": "U Phyllodes",
    "phyllodes tumour": "U Phyllodes",
    "gastric adenocarcinoma": "Ung thư biểu mô tuyến dạ dày",
    "gastric carcinomas": "Các ung thư biểu mô dạ dày",
    "gastric squamous cell carcinoma": "Ung thư biểu mô tế bào vảy dạ dày",
    "gastric adenosquamous carcinoma": "Ung thư biểu mô tuyến-vảy dạ dày",
    "gastric undifferentiated carcinoma": "Ung thư biểu mô không biệt hóa dạ dày",
    "gastric neuroendocrine neoplasms": "Tân sinh thần kinh nội tiết dạ dày",
    "gastric dysplasia": "Loạn sản dạ dày",
    "gastric hyperplastic polyps": "Polyp tăng sản dạ dày",
    "fundic gland polyps": "Polyp tuyến đáy vị",
    "gastric pyloric gland adenoma": "U tuyến môn vị dạ dày",
    "oxyntic gland adenoma": "U tuyến sinh acid",
    "gastrointestinal stromal tumors": "U mô đệm đường tiêu hóa",
    "gastrointestinal stromal tumours": "U mô đệm đường tiêu hóa",
    "adenocarcinoma of the oesophagus and oesophagogastric junction": "Ung thư biểu mô tuyến thực quản và chỗ nối thực quản-dạ dày",
    "adenocarcinoma of the esophagus and esophagogastric junction": "Ung thư biểu mô tuyến thực quản và chỗ nối thực quản-dạ dày",
    "papillary thyroid carcinoma": "Ung thư biểu mô tuyến giáp thể nhú",
    "follicular thyroid carcinoma": "Ung thư biểu mô tuyến giáp thể nang",
    "medullary thyroid carcinoma": "Ung thư biểu mô tuyến giáp thể tủy",
    "anaplastic thyroid carcinoma": "Ung thư biểu mô tuyến giáp không biệt hóa",
    "follicular adenoma": "U tuyến thể nang",
    "hashimoto thyroiditis": "Viêm tuyến giáp Hashimoto",
    "subacute granulomatous thyroiditis": "Viêm tuyến giáp bán cấp dạng hạt",
    "nodular hyperplasia": "Quá sản dạng nốt",
    "adenocarcinoma in situ of the lung": "Ung thư biểu mô tuyến tại chỗ của phổi",
    "invasive non-mucinous adenocarcinoma of the lung": "Ung thư biểu mô tuyến không nhầy xâm nhập của phổi",
    "invasive mucinous adenocarcinoma of the lung": "Ung thư biểu mô tuyến dạng nhầy xâm nhập của phổi",
    "minimally invasive adenocarcinoma of the lung": "Ung thư biểu mô tuyến xâm nhập tối thiểu của phổi",
    "squamous cell carcinoma of the lung": "Ung thư biểu mô tế bào vảy của phổi",
    "small cell carcinoma of the lung": "Ung thư biểu mô tế bào nhỏ của phổi",
    "large cell neuroendocrine carcinoma": "Ung thư biểu mô thần kinh nội tiết tế bào lớn",
    "typical carcinoid tumor": "U carcinoid điển hình",
    "typical carcinoid tumour": "U carcinoid điển hình",
    "atypical carcinoid tumor": "U carcinoid không điển hình",
    "atypical carcinoid tumour": "U carcinoid không điển hình",
    "colorectal adenocarcinoma": "Ung thư biểu mô tuyến đại trực tràng",
    "mucinous colorectal adenocarcinoma": "Ung thư biểu mô tuyến dạng nhầy đại trực tràng",
    "signet-ring cell carcinoma": "Ung thư biểu mô tế bào nhẫn",
    "sessile serrated lesion": "Tổn thương răng cưa không cuống",
    "traditional serrated adenoma": "U tuyến răng cưa truyền thống",
    "tubular adenoma": "U tuyến dạng ống",
    "tubulovillous adenoma": "U tuyến ống-nhung mao",
    "villous adenoma": "U tuyến nhung mao",
    "hepatocellular carcinoma": "Ung thư biểu mô tế bào gan",
    "intrahepatic cholangiocarcinoma": "Ung thư biểu mô đường mật trong gan",
    "pancreatic ductal adenocarcinoma": "Ung thư biểu mô tuyến ống tụy",
    "clear cell renal cell carcinoma": "Ung thư biểu mô tế bào thận típ tế bào sáng",
    "papillary renal cell carcinoma": "Ung thư biểu mô tế bào thận thể nhú",
    "chromophobe renal cell carcinoma": "Ung thư biểu mô tế bào thận kỵ màu",
    "urothelial carcinoma": "Ung thư biểu mô niệu",
    "prostatic adenocarcinoma": "Ung thư biểu mô tuyến tiền liệt",
    "cervical squamous cell carcinoma": "Ung thư biểu mô tế bào vảy cổ tử cung",
    "endometrioid carcinoma": "Ung thư biểu mô dạng nội mạc tử cung",
    "high-grade serous carcinoma": "Ung thư biểu mô thanh dịch độ cao",
    "low-grade serous carcinoma": "Ung thư biểu mô thanh dịch độ thấp",
    "clear cell carcinoma": "Ung thư biểu mô tế bào sáng",
    "basal cell carcinoma": "Ung thư biểu mô tế bào đáy",
    "cutaneous squamous cell carcinoma": "Ung thư biểu mô tế bào vảy da",
    "cutaneous melanoma": "U hắc tố ác tính da",
    "seborrheic keratosis": "Dày sừng tiết bã",
    "actinic keratosis": "Dày sừng ánh sáng",
    "melanocytic nevus": "Nơvi tế bào hắc tố",
    "melanocytic naevus": "Nơvi tế bào hắc tố",
    "dermatofibroma": "U xơ bì",
    "diffuse large b-cell lymphoma": "U lympho tế bào B lớn lan tỏa",
    "follicular lymphoma": "U lympho thể nang",
    "mantle cell lymphoma": "U lympho tế bào vùng áo",
    "marginal zone lymphoma": "U lympho vùng rìa",
    "classical hodgkin lymphoma": "U lympho Hodgkin kinh điển",
    "chronic lymphocytic leukaemia": "Bệnh bạch cầu lympho mạn",
    "chronic lymphocytic leukemia": "Bệnh bạch cầu lympho mạn",
    "acute myeloid leukaemia": "Bệnh bạch cầu cấp dòng tủy",
    "acute myeloid leukemia": "Bệnh bạch cầu cấp dòng tủy",
    "glioblastoma": "U nguyên bào thần kinh đệm",
    "meningioma": "U màng não",
    "schwannoma": "U bao Schwann",
    "retinoblastoma": "U nguyên bào võng mạc",
    "pleomorphic adenoma": "U tuyến đa hình",
    "warthin tumor": "U Warthin",
    "warthin tumour": "U Warthin",
    "nasopharyngeal carcinoma": "Ung thư biểu mô vòm mũi họng",
    "oral squamous cell carcinoma": "Ung thư biểu mô tế bào vảy khoang miệng",
    "leiomyoma": "U cơ trơn",
    "leiomyosarcoma": "Sarcoma cơ trơn",
    "lipoma": "U mỡ",
    "liposarcoma": "Sarcoma mỡ",
    "neurofibroma": "U xơ thần kinh",
    "rhabdomyosarcoma": "Sarcoma cơ vân",
    "osteosarcoma": "Sarcoma xương",
    "chondrosarcoma": "Sarcoma sụn",
    "angiosarcoma": "Sarcoma mạch",
    "granular cell tumor": "U tế bào hạt",
    "granular cell tumour": "U tế bào hạt",
    "granulomatous disorders": "Các bệnh lý dạng hạt",
    "pecoma": "U PEComa",
    "meningiomas": "Các u màng não",
    "carcinosarcoma": "Ung thư biểu mô-sarcoma",
    "lymphomas": "Các u lympho",
    "cholangitis": "Viêm đường mật",
    "groove/paraduodenal pancreatitis": "Viêm tụy vùng rãnh/cạnh tá tràng",
    "pseudocysts": "Nang giả",
    "lymphangioma": "U mạch bạch huyết",
    "cholangiocarcinoma": "Ung thư biểu mô đường mật",
    "pancreatoblastoma": "U nguyên bào tụy",
    "ischaemic fasciitis": "Viêm cân mạc thiếu máu cục bộ",
    "ischemic fasciitis": "Viêm cân mạc thiếu máu cục bộ",
    "hibernoma": "U mỡ nâu",
    "lipoblastoma": "U nguyên bào mỡ",
    "fibromatosis": "Bệnh u xơ",
    "elastofibroma": "U xơ chun",
    "haemangiomas": "Các u máu",
    "hemangiomas": "Các u máu",
    "perineurioma": "U tế bào quanh thần kinh",
    "myofibroblastoma": "U nguyên bào sợi-cơ",
    "myositis ossificans": "Viêm cơ cốt hóa",
    "rhabdomyoma": "U cơ vân",
    "dermatofibrosarcoma protuberans": "Sarcoma sợi bì lồi",
    "myoepithelial neoplasms": "Tân sinh cơ-biểu mô",
    "myxofibrosarcoma": "Sarcoma xơ nhầy",
    "chordoma": "U nguyên sống",
    "hepatoblastoma": "U nguyên bào gan",
    "biliary adenofibroma": "U tuyến-xơ đường mật",
    "adenomyoepithelioma": "U tuyến-cơ biểu mô",
    "blood vessels": "Mạch máu",
    "aneurysms": "Phình mạch",
    "atherosclerosis": "Xơ vữa động mạch",
    "vasculitis": "Viêm mạch",
    "cardiomyopathies": "Bệnh cơ tim",
    "endocarditis": "Viêm nội tâm mạc",
    "myocarditis": "Viêm cơ tim",
    "pericarditis": "Viêm màng ngoài tim",
    "adrenals": "Tuyến thượng thận",
    "adrenal": "Tuyến thượng thận",
    "adrenal hemorrhage": "Xuất huyết tuyến thượng thận",
    "adrenal histology": "Mô học tuyến thượng thận",
    "lymph nodes": "Hạch lympho",
    "respiratory tract": "Đường hô hấp",
    "salivary glands": "Tuyến nước bọt",
    "urinary tract": "Đường tiết niệu",
    "gynecologic tract": "Đường sinh dục nữ",
    "non neoplastic dermpath i": "Bệnh học da không tân sinh I",
    "non neoplastic dermpath ii": "Bệnh học da không tân sinh II",
    "acantholytic disorders": "Các bệnh lý tiêu gai",
    "idiopathic connective tissue diseases": "Bệnh mô liên kết vô căn",
    "vesiculo bullous dermatoses": "Bệnh da mụn nước-bọng nước",
    "disorders of collagen": "Bệnh lý collagen",
    "disorders of elastic tissue": "Bệnh lý mô chun",
    "disorders of keratiniziation": "Bệnh lý sừng hóa",
    "disorders of keratinization": "Bệnh lý sừng hóa",
    "disorders of pigmentation": "Rối loạn sắc tố",
    "ganglioneuroblastoma": "U nguyên bào hạch thần kinh",
    "ganglioneuroma": "U hạch thần kinh",
    "heterotopic adrenal tissue": "Mô thượng thận lạc chỗ",
    "myelolipoma": "U tủy-mỡ",
    "neuroblastoma": "U nguyên bào thần kinh",
    "pheochromocytoma": "U tủy thượng thận",
    "gastrinoma": "U tiết gastrin",
    "glucagonoma": "U tiết glucagon",
    "insulinoma": "U tiết insulin",
    "non functioning pannets": "U thần kinh nội tiết tụy không chức năng",
    "somatostatinoma": "U tiết somatostatin",
    "vipoma": "U tiết VIP",
    "parathyroid": "Tuyến cận giáp",
    "hyperparathyroidism": "Cường cận giáp",
    "pituitary": "Tuyến yên",
    "craniopharyngioma": "U sọ-hầu",
    "thyroiditis": "Viêm tuyến giáp",
    "galactocele": "Nang sữa",
    "inflammatory and reactive changes in glandular cells and squamous cells": "Biến đổi viêm và phản ứng ở tế bào tuyến và tế bào vảy",
    "normal pancreatic and biliary parenchyma and contaminants": "Nhu mô tụy, đường mật bình thường và thành phần ngoại lai",
    "ultrasound guidance of fnab": "Hướng dẫn chọc hút kim nhỏ dưới siêu âm",
    "introduction: the role of ancillary testing": "Đại cương: vai trò của xét nghiệm bổ trợ",
    "atypical lipomatous tumour / well-differentiated liposarcoma": "U mỡ không điển hình / sarcoma mỡ biệt hóa tốt",
    "epidermoid metaplasia of the oesophagus": "Chuyển sản dạng biểu bì của thực quản",
    "epidermoid metaplasia of the esophagus": "Chuyển sản dạng biểu bì của thực quản",
    "cancer of unknown primary site": "Ung thư chưa rõ vị trí nguyên phát",
    "b-lymphoblastic leukaemia/lymphoma": "Bệnh bạch cầu/u lympho nguyên bào lympho B",
    "b-lymphoblastic leukemia/lymphoma": "Bệnh bạch cầu/u lympho nguyên bào lympho B",
    "t-lymphoblastic leukaemia/lymphoma": "Bệnh bạch cầu/u lympho nguyên bào lympho T",
    "t-lymphoblastic leukemia/lymphoma": "Bệnh bạch cầu/u lympho nguyên bào lympho T",
    "chronic lymphocytic leukaemia / small lymphocytic lymphoma": "Bệnh bạch cầu lympho mạn / u lympho lympho bào nhỏ",
    "chronic lymphocytic leukemia / small lymphocytic lymphoma": "Bệnh bạch cầu lympho mạn / u lympho lympho bào nhỏ",
    "squamous cell carcinoma in situ (bowen disease)": "Ung thư biểu mô tế bào vảy tại chỗ (bệnh Bowen)",
    "naevoid basal cell carcinoma syndrome (gorlin syndrome)": "Hội chứng ung thư biểu mô tế bào đáy dạng nơvi (hội chứng Gorlin)",
    "naevoid basal cell carcinoma syndrome - gorlin syndrome (ptch1, sufu, gpr161)": "Hội chứng ung thư biểu mô tế bào đáy dạng nơvi - hội chứng Gorlin (PTCH1, SUFU, GPR161)",
    "cytopathology 1": "Tế bào học 1",
    "cytopathology 2": "Tế bào học 2",
    "anus": "Hậu môn",
    "appendicitis": "Viêm ruột thừa",
    "cholecystitis": "Viêm túi mật",
    "cholelithiasis": "Sỏi túi mật",
    "cholesterolosis hydrops mucocele": "Lắng đọng cholesterol, túi mật căng nước và túi nhầy",
    "pathology of extrahepatic bile ducts": "Bệnh học đường mật ngoài gan",
    "hematolymphoid malignancies": "Bệnh ác tính hệ tạo máu và lympho",
    "cirrhosis": "Xơ gan",
    "hepatitis hepatotropic viruses": "Viêm gan do virus hướng gan",
    "transplantation pathology": "Bệnh học ghép tạng",
    "developmental anomalies": "Bất thường phát triển",
    "malabsorption": "Kém hấp thu",
    "misc non neoplastic diseases": "Các bệnh không tân sinh khác",
    "external genitalia": "Cơ quan sinh dục ngoài",
    "balanitis xerotica obliterans": "Viêm quy đầu xơ tắc nghẽn",
    "condyloma acuminata": "Sùi mào gà",
    "condyloma acuminatum": "Sùi mào gà",
    "idiopathic scrotal calcinosis": "Vôi hóa bìu vô căn",
    "molluscum contagiosum": "U mềm lây",
    "verruciform xanthoma": "U vàng dạng mụn cóc",
    "tubulointerstitial diseases i": "Bệnh ống thận-mô kẽ I",
    "tubulointerstitial diseases ii": "Bệnh ống thận-mô kẽ II",
    "histology of testes": "Mô học tinh hoàn",
    "inflammation": "Viêm",
    "histology of bladder": "Mô học bàng quang",
    "inflammation cystitis": "Viêm bàng quang",
    "urine cytology": "Tế bào học nước tiểu",
    "cervix": "Cổ tử cung",
    "uterus": "Tử cung",
    "adenomyosis": "Lạc nội mạc tử cung trong cơ tử cung",
    "ear": "Tai",
    "eye": "Mắt",
    "glaucoma": "Glôcôm",
    "lens": "Thể thủy tinh",
    "ocular trauma": "Chấn thương mắt",
    "optic nerve": "Dây thần kinh thị giác",
    "larynx": "Thanh quản",
    "carcinoid": "U carcinoid",
    "maxillofacial": "Hàm mặt",
    "ameloblastoma": "U nguyên bào men",
    "odontoma": "U răng",
    "hematopoietic lymphoid pathology": "Bệnh học hệ tạo máu và lympho",
    "oral manifestations of systemic diseases": "Biểu hiện tại miệng của bệnh hệ thống",
    "bacterial lymphadenitides": "Viêm hạch do vi khuẩn",
    "fungal lymphadenitides": "Viêm hạch do nấm",
    "mycobacterial lymphadenitides": "Viêm hạch do Mycobacterium",
    "protozoal lymphadenitides": "Viêm hạch do đơn bào",
    "viral lymphadenitides": "Viêm hạch do virus",
    "lymphadenopathies i": "Bệnh lý hạch I",
    "lymphadenopathies ii": "Bệnh lý hạch II",
    "non neoplastic histiocytic proliferations": "Tăng sinh mô bào không tân sinh",
    "hypersplenism": "Cường lách",
    "acid fast bacilli": "Trực khuẩn kháng acid",
    "filamentous fungi molds": "Nấm sợi và nấm mốc",
    "superficial mycoses": "Nấm nông",
    "rapidly growing mycobacteria": "Mycobacterium phát triển nhanh",
    "desmoid fibromatosis": "U xơ desmoid",
    "paragangliomas": "Các u cận hạch",
    "angiomatosis": "Bệnh đa u mạch",
    "gynaecomastia": "Vú to ở nam giới",
    "gynecomastia": "Vú to ở nam giới",
    "polycythaemia vera": "Đa hồng cầu nguyên phát",
    "essential thrombocythaemia": "Tăng tiểu cầu nguyên phát",
    "essential thrombocythemia": "Tăng tiểu cầu nguyên phát",
    "plasmacytoma": "U tương bào",
    "mycosis fungoides": "U sùi dạng nấm",
    "ataxia-telangiectasia": "Thất điều-giãn mạch",
    "fanconi anaemia": "Thiếu máu Fanconi",
    "fanconi anemia": "Thiếu máu Fanconi",
    "tuberous sclerosis": "Xơ cứng củ",
    "seminoma": "U tinh bào",
    "choriocarcinoma": "Ung thư biểu mô màng đệm",
    "thecoma": "U vỏ bào",
    "dysgerminoma": "U nghịch mầm",
    "struma ovarii": "Bướu giáp buồng trứng",
    "gonadoblastoma": "U nguyên bào sinh dục",
    "pseudomyxoma peritonei": "Giả u nhầy phúc mạc",
    "salpingitis isthmica nodosa": "Viêm vòi tử cung eo dạng nốt",
    "partial hydatidiform mole": "Thai trứng bán phần",
    "complete hydatidiform mole": "Thai trứng toàn phần"
  };

  const sites = [
    ["oesophagogastric junction", "chỗ nối thực quản-dạ dày"],
    ["esophagogastric junction", "chỗ nối thực quản-dạ dày"],
    ["gastro-oesophageal junction", "chỗ nối thực quản-dạ dày"],
    ["gastroesophageal junction", "chỗ nối thực quản-dạ dày"],
    ["central nervous system", "hệ thần kinh trung ương"],
    ["peripheral nerve sheath", "bao dây thần kinh ngoại biên"],
    ["pancreaticobiliary tract", "đường tụy-mật"],
    ["biliary tract", "đường mật"],
    ["upper urinary tract", "đường tiết niệu trên"],
    ["female genital tract", "đường sinh dục nữ"],
    ["male genital tract", "đường sinh dục nam"],
    ["gastrointestinal tract", "đường tiêu hóa"],
    ["head and neck", "đầu và cổ"],
    ["soft tissue", "mô mềm"],
    ["uterine cervix", "cổ tử cung"],
    ["uterine corpus", "thân tử cung"],
    ["salivary gland", "tuyến nước bọt"],
    ["lacrimal gland", "tuyến lệ"],
    ["thyroid gland", "tuyến giáp"],
    ["parathyroid gland", "tuyến cận giáp"],
    ["adrenal gland", "tuyến thượng thận"],
    ["pituitary gland", "tuyến yên"],
    ["mammary gland", "tuyến vú"],
    ["lymph node", "hạch lympho"],
    ["bone marrow", "tủy xương"],
    ["small intestine", "ruột non"],
    ["large intestine", "ruột già"],
    ["oral cavity", "khoang miệng"],
    ["nasal cavity", "hốc mũi"],
    ["paranasal sinus", "xoang cạnh mũi"],
    ["urinary bladder", "bàng quang"],
    ["renal pelvis", "bể thận"],
    ["fallopian tube", "vòi tử cung"],
    ["endometrium", "nội mạc tử cung"],
    ["myometrium", "cơ tử cung"],
    ["mediastinum", "trung thất"],
    ["peritoneum", "phúc mạc"],
    ["retroperitoneum", "sau phúc mạc"],
    ["pleura", "màng phổi"],
    ["pericardium", "màng tim"],
    ["conjunctiva", "kết mạc"],
    ["ciliary body", "thể mi"],
    ["optic nerve", "dây thần kinh thị giác"],
    ["optic disc", "đĩa thị"],
    ["eyelid", "mi mắt"],
    ["cornea", "giác mạc"],
    ["iris", "mống mắt"],
    ["uveal", "màng bồ đào"],
    ["orbit", "hốc mắt"],
    ["retina", "võng mạc"],
    ["breast", "vú"],
    ["mammary", "vú"],
    ["lung", "phổi"],
    ["pulmonary", "phổi"],
    ["thoracic", "lồng ngực"],
    ["thyroid", "tuyến giáp"],
    ["gastric", "dạ dày"],
    ["stomach", "dạ dày"],
    ["oesophageal", "thực quản"],
    ["esophageal", "thực quản"],
    ["oesophagus", "thực quản"],
    ["esophagus", "thực quản"],
    ["duodenal", "tá tràng"],
    ["duodenum", "tá tràng"],
    ["jejunal", "hỗng tràng"],
    ["ileal", "hồi tràng"],
    ["appendiceal", "ruột thừa"],
    ["appendix", "ruột thừa"],
    ["colorectal", "đại trực tràng"],
    ["colonic", "đại tràng"],
    ["colon", "đại tràng"],
    ["rectal", "trực tràng"],
    ["rectum", "trực tràng"],
    ["hepatic", "gan"],
    ["liver", "gan"],
    ["pancreatic", "tụy"],
    ["pancreas", "tụy"],
    ["gallbladder", "túi mật"],
    ["renal", "thận"],
    ["kidney", "thận"],
    ["prostatic", "tuyến tiền liệt"],
    ["prostate", "tuyến tiền liệt"],
    ["testicular", "tinh hoàn"],
    ["testis", "tinh hoàn"],
    ["ovarian", "buồng trứng"],
    ["ovary", "buồng trứng"],
    ["cervical", "cổ tử cung"],
    ["endometrial", "nội mạc tử cung"],
    ["uterine", "tử cung"],
    ["vaginal", "âm đạo"],
    ["vagina", "âm đạo"],
    ["vulvar", "âm hộ"],
    ["vulval", "âm hộ"],
    ["vulva", "âm hộ"],
    ["cutaneous", "da"],
    ["skin", "da"],
    ["cerebral", "não"],
    ["brain", "não"],
    ["spinal cord", "tủy sống"],
    ["bone", "xương"],
    ["cardiac", "tim"],
    ["heart", "tim"],
    ["thymic", "tuyến ức"],
    ["thymus", "tuyến ức"],
    ["splenic", "lách"],
    ["spleen", "lách"]
  ];

  const phrases = [
    ["non-invasive", "không xâm nhập"],
    ["intrahepatic", "trong gan"],
    ["extrahepatic", "ngoài gan"],
    ["small duct", "ống nhỏ"],
    ["large duct", "ống lớn"],
    ["pleuropulmonary", "màng phổi-phổi"],
    ["sinonasal", "mũi-xoang"],
    ["nasopharyngeal", "vòm mũi họng"],
    ["adrenocortical", "vỏ thượng thận"],
    ["parathyroid", "tuyến cận giáp"],
    ["pituitary", "tuyến yên"],
    ["sellar", "vùng yên"],
    ["conjunctival", "kết mạc"],
    ["epibulbar", "trên nhãn cầu"],
    ["ocular", "mắt"],
    ["orbital", "hốc mắt"],
    ["optic", "thị giác"],
    ["retinal", "võng mạc"],
    ["uveal", "màng bồ đào"],
    ["iris", "mống mắt"],
    ["minimally invasive", "xâm nhập tối thiểu"],
    ["widely invasive", "xâm nhập rộng"],
    ["locally advanced", "tiến triển tại chỗ"],
    ["high-grade", "độ cao"],
    ["low-grade", "độ thấp"],
    ["well-differentiated", "biệt hóa tốt"],
    ["moderately differentiated", "biệt hóa vừa"],
    ["poorly differentiated", "kém biệt hóa"],
    ["undifferentiated", "không biệt hóa"],
    ["neuroendocrine", "thần kinh nội tiết"],
    ["lymphoepithelioma-like", "dạng biểu mô-lympho"],
    ["acinar cell", "tế bào nang tuyến"],
    ["round cell", "tế bào tròn"],
    ["columnar cell", "tế bào trụ"],
    ["tall cell", "tế bào cao"],
    ["chief cell", "tế bào chính"],
    ["hurthle cell", "tế bào Hürthle"],
    ["sertoli cell", "tế bào Sertoli"],
    ["leydig cell", "tế bào Leydig"],
    ["granulosa cell", "tế bào hạt"],
    ["schwann cell", "tế bào Schwann"],
    ["signet-ring cell", "tế bào nhẫn"],
    ["clear cell", "tế bào sáng"],
    ["atypical spindle cell", "tế bào hình thoi không điển hình"],
    ["spindle cell", "tế bào hình thoi"],
    ["small cell", "tế bào nhỏ"],
    ["large cell", "tế bào lớn"],
    ["giant cell", "tế bào khổng lồ"],
    ["granular cell", "tế bào hạt"],
    ["basal cell", "tế bào đáy"],
    ["squamous cell", "tế bào vảy"],
    ["b-cell", "tế bào B"],
    ["t-cell", "tế bào T"],
    ["nk-cell", "tế bào NK"],
    ["germ cell", "tế bào mầm"],
    ["dendritic cell", "tế bào tua"],
    ["plasma cell", "tương bào"],
    ["smooth muscle", "cơ trơn"],
    ["skeletal muscle", "cơ vân"],
    ["intraepithelial", "trong biểu mô"],
    ["intraductal", "nội ống"],
    ["intravascular", "nội mạch"],
    ["invasive", "xâm nhập"],
    ["metastatic", "di căn"],
    ["malignant", "ác tính"],
    ["benign", "lành tính"],
    ["borderline", "giáp biên"],
    ["atypical", "không điển hình"],
    ["papillary", "thể nhú"],
    ["follicular", "thể nang"],
    ["mucinous", "dạng nhầy"],
    ["serous", "thanh dịch"],
    ["endometrioid", "dạng nội mạc tử cung"],
    ["oncocytic", "tế bào ưa acid"],
    ["chromophobe", "kỵ màu"],
    ["adenoid cystic", "dạng tuyến nang"],
    ["adenosquamous", "tuyến-vảy"],
    ["mucoepidermoid", "nhầy-biểu bì"],
    ["pleomorphic", "đa hình"],
    ["epithelioid", "dạng biểu mô"],
    ["sarcomatoid", "dạng sarcoma"],
    ["rhabdoid", "dạng rhabdoid"],
    ["desmoplastic", "xơ hóa"],
    ["sclerosing", "xơ hóa"],
    ["myxoid", "dạng nhầy"],
    ["cystic", "dạng nang"],
    ["solid", "dạng đặc"],
    ["cribriform", "dạng sàng"],
    ["tubular", "dạng ống"],
    ["micropapillary", "vi nhú"],
    ["diffuse", "lan tỏa"],
    ["nodular", "dạng nốt"],
    ["juvenile", "thiếu niên"],
    ["infantile", "trẻ nhũ nhi"],
    ["congenital", "bẩm sinh"],
    ["hereditary", "di truyền"],
    ["familial", "gia đình"],
    ["primary", "nguyên phát"],
    ["secondary", "thứ phát"],
    ["acute", "cấp"],
    ["chronic", "mạn"],
    ["myeloid", "dòng tủy"],
    ["lymphoblastic", "nguyên bào lympho"],
    ["lymphocytic", "lympho bào"],
    ["myelodysplastic", "loạn sản tủy"],
    ["myeloproliferative", "tăng sinh tủy"],
    ["lymphoproliferative", "tăng sinh lympho"],
    ["odontogenic", "do răng"],
    ["adamantinomatous", "dạng men răng"],
    ["olfactory", "khứu giác"],
    ["oral", "miệng"],
    ["proliferative", "tăng sinh"],
    ["verrucous", "dạng mụn cóc"],
    ["submucous", "dưới niêm mạc"],
    ["conventional", "thông thường"],
    ["classic", "kinh điển"],
    ["systemic", "hệ thống"],
    ["desmoid", "desmoid"],
    ["plexiform", "dạng đám rối"],
    ["lymphatic", "bạch huyết"],
    ["venous", "tĩnh mạch"],
    ["arteriovenous", "động-tĩnh mạch"],
    ["deep penetrating", "xâm nhập sâu"],
    ["combined", "phối hợp"],
    ["ectopic", "lạc chỗ"],
    ["osseous", "dạng xương"],
    ["arsenical", "do arsen"],
    ["solar", "ánh sáng"],
    ["warty", "dạng mụn cóc"],
    ["dysplastic", "loạn sản"],
    ["recurrent", "tái phát"],
    ["acral", "đầu chi"],
    ["genital", "sinh dục"],
    ["blue", "xanh"],
    ["halo", "quầng"],
    ["clonal", "dòng tế bào"],
    ["undetermined significance", "ý nghĩa chưa xác định"],
    ["essential", "tiên phát"],
    ["activated", "hoạt hóa"],
    ["altered", "biến đổi"],
    ["histologically defined", "xác định bằng mô học"],
    ["non-wnt/non-shh", "không WNT/không SHH"],
    ["intermixed", "hỗn hợp"],
    ["localized", "khu trú"],
    ["adult", "người lớn"],
    ["metaplastic", "chuyển sản"],
    ["gestational", "thai kỳ"],
    ["pregnancy", "thai kỳ"],
    ["disseminated", "lan tỏa"],
    ["intravenous", "trong tĩnh mạch"],
    ["partial", "bán phần"],
    ["complete", "toàn phần"],
    ["hydatidiform mole", "thai trứng"],
    ["melanocytic", "tế bào hắc tố"],
    ["vascular", "mạch máu"],
    ["fibrous", "xơ"],
    ["stromal", "mô đệm"],
    ["epithelial", "biểu mô"],
    ["mesenchymal", "trung mô"],
    ["inflammatory", "viêm"],
    ["reactive", "phản ứng"],
    ["precursor", "tiền thân"],
    ["predisposition", "khuynh hướng mắc bệnh"],
    ["associated", "liên quan"],
    ["related", "liên quan"],
    ["genetic alterations", "biến đổi di truyền"],
    ["molecular alterations", "biến đổi phân tử"],
    ["rearranged", "tái sắp xếp"],
    ["rearrangement", "tái sắp xếp"],
    ["fusion", "dung hợp"],
    ["mutant", "đột biến"],
    ["deficient", "thiếu hụt"],
    ["positive", "dương tính"],
    ["negative", "âm tính"],
    ["not otherwise specified", "không đặc hiệu khác"],
    ["risk of malignancy", "nguy cơ ác tính"],
    ["diagnostic management recommendations", "khuyến nghị xử trí chẩn đoán"],
    ["sample reports", "báo cáo mẫu"],
    ["ancillary testing", "xét nghiệm bổ trợ"],
    ["molecular testing", "xét nghiệm phân tử"],
    ["flow cytometry", "đo tế bào dòng chảy"],
    ["immunocytochemistry", "hóa miễn dịch tế bào"],
    ["immunohistochemistry", "hóa mô miễn dịch"],
    ["ultrasound guidance", "hướng dẫn siêu âm"],
    ["rapid onsite evaluation", "đánh giá nhanh tại chỗ"],
    ["cell preparation methods", "phương pháp chuẩn bị tế bào"],
    ["insufficient", "không đủ"],
    ["inadequate", "không đạt"],
    ["non-diagnostic", "không chẩn đoán được"],
    ["suspicious for malignancy", "nghi ngờ ác tính"],
    ["normal", "bình thường"],
    ["parenchyma", "nhu mô"],
    ["contaminants", "thành phần ngoại lai"],
    ["biliary", "đường mật"],
    ["pancreatitis", "viêm tụy"],
    ["fasciitis", "viêm cân mạc"],
    ["cholangitis", "viêm đường mật"],
    ["dedifferentiated", "mất biệt hóa"],
    ["extraskeletal", "ngoài xương"],
    ["synovial", "hoạt dịch"],
    ["intimal", "nội mạc"],
    ["embryonal", "phôi"],
    ["alveolar", "dạng hốc"],
    ["lipomatous", "dạng mỡ"],
    ["fibroblastic", "nguyên bào sợi"],
    ["myofibroblastic", "nguyên bào sợi-cơ"],
    ["fibromyxoid", "xơ-nhầy"],
    ["haematologic", "huyết học"],
    ["hematologic", "huyết học"],
    ["colorectum", "đại trực tràng"],
    ["digestive tract", "đường tiêu hóa"],
    ["bowel", "ruột"],
    ["anal", "hậu môn"],
    ["squamous", "dạng vảy"],
    ["glandular", "tuyến"],
    ["gland", "tuyến"],
    ["cell", "tế bào"],
    ["cancer", "ung thư"],
    ["malignancy", "ác tính"],
    ["tumour", "u"],
    ["tumor", "u"],
    ["neoplasms", "các tân sinh"],
    ["neoplasm", "tân sinh"],
    ["syndromes", "các hội chứng"],
    ["syndrome", "hội chứng"],
    ["disorders", "các bệnh lý"],
    ["disorder", "bệnh lý"],
    ["changes", "biến đổi"],
    ["change", "biến đổi"],
    ["methods", "phương pháp"],
    ["method", "phương pháp"],
    ["introduction", "đại cương"],
    ["definition", "định nghĩa"],
    ["category", "nhóm"],
    ["recommendations", "khuyến nghị"],
    ["guidance", "hướng dẫn"],
    ["preparation", "chuẩn bị"],
    ["testing", "xét nghiệm"],
    ["role", "vai trò"],
    ["including", "bao gồm"],
    ["differentiation", "biệt hóa"],
    ["metaplasia", "chuyển sản"],
    ["epithelium", "biểu mô"],
    ["epidermoid", "dạng biểu bì"],
    ["pigment", "sắc tố"],
    ["cells", "tế bào"],
    ["disease", "bệnh"],
    ["site", "vị trí"],
    ["unknown", "chưa rõ"],
    ["postradiation", "sau xạ trị"],
    ["dermal", "ở da"],
    ["special-site", "ở vị trí đặc biệt"],
    ["axilla", "nách"],
    ["scalp", "da đầu"],
    ["ear", "tai"],
    ["indolent", "diễn tiến chậm"],
    ["gi tract", "đường tiêu hóa"],
    ["hypertrophy", "phì đại"],
    ["involvement", "xâm nhập"],
    ["palisaded", "xếp hàng rào"],
    ["intranodal", "trong hạch"],
    ["histiocytic", "mô bào"],
    ["mast", "dưỡng bào"],
    ["interdigitating", "xen kẽ"],
    ["hyperdiploidy", "tăng bội"],
    ["hypodiploidy", "giảm bội"],
    ["to the", "đến"],
    ["to", "đến"],
    ["of", "của"],
    ["in", "trong"],
    ["the", ""],
    ["in situ", "tại chỗ"],
    ["of the", "của"],
    ["associated with", "liên quan với"],
    ["arising in", "phát sinh trên"],
    ["with", "có"],
    ["without", "không có"],
    ["and", "và"],
    ["type", "típ"],
    ["variant", "biến thể"],
    ["multiple", "nhiều"],
    ["other", "khác"],
    ["miscellaneous", "khác"],
    ["lesions", "tổn thương"],
    ["lesion", "tổn thương"],
    ["metastases", "di căn"],
    ["metastasis", "di căn"],
    ["infections", "nhiễm trùng"],
    ["infection", "nhiễm trùng"]
  ];

  const heads = [
    ["squamous cell carcinomas", "Các ung thư biểu mô tế bào vảy"],
    ["neuroendocrine carcinomas", "Các ung thư biểu mô thần kinh nội tiết"],
    ["adenocarcinomas", "Các ung thư biểu mô tuyến"],
    ["carcinomas", "Các ung thư biểu mô"],
    ["lymphomas", "Các u lympho"],
    ["leukaemias", "Các bệnh bạch cầu"],
    ["leukemias", "Các bệnh bạch cầu"],
    ["sarcomas", "Các sarcoma"],
    ["rhabdomyosarcomas", "Các sarcoma cơ vân"],
    ["adenomas", "Các u tuyến"],
    ["papillomas", "Các u nhú"],
    ["meningiomas", "Các u màng não"],
    ["neoplasms", "Các tân sinh"],
    ["hyperplasias", "Các quá sản"],
    ["dysplasias", "Các loạn sản"],
    ["cysts", "Các nang"],
    ["polyps", "Các polyp"],
    ["large cell neuroendocrine carcinoma", "Ung thư biểu mô thần kinh nội tiết tế bào lớn"],
    ["small cell neuroendocrine carcinoma", "Ung thư biểu mô thần kinh nội tiết tế bào nhỏ"],
    ["squamous cell carcinoma", "Ung thư biểu mô tế bào vảy"],
    ["basal cell carcinoma", "Ung thư biểu mô tế bào đáy"],
    ["neuroendocrine carcinoma", "Ung thư biểu mô thần kinh nội tiết"],
    ["renal cell carcinoma", "Ung thư biểu mô tế bào thận"],
    ["hepatocellular carcinoma", "Ung thư biểu mô tế bào gan"],
    ["urothelial carcinoma", "Ung thư biểu mô niệu"],
    ["adenoid cystic carcinoma", "Ung thư biểu mô dạng tuyến nang"],
    ["mucoepidermoid carcinoma", "Ung thư biểu mô nhầy-biểu bì"],
    ["adenosquamous carcinoma", "Ung thư biểu mô tuyến-vảy"],
    ["adenocarcinoma", "Ung thư biểu mô tuyến"],
    ["carcinoma", "Ung thư biểu mô"],
    ["lymphoblastic leukaemia", "Bệnh bạch cầu nguyên bào lympho"],
    ["lymphoblastic leukemia", "Bệnh bạch cầu nguyên bào lympho"],
    ["myeloid leukaemia", "Bệnh bạch cầu dòng tủy"],
    ["myeloid leukemia", "Bệnh bạch cầu dòng tủy"],
    ["leukaemia", "Bệnh bạch cầu"],
    ["leukemia", "Bệnh bạch cầu"],
    ["lymphoma", "U lympho"],
    ["liposarcoma", "Sarcoma mỡ"],
    ["leiomyosarcoma", "Sarcoma cơ trơn"],
    ["rhabdomyosarcoma", "Sarcoma cơ vân"],
    ["chondrosarcoma", "Sarcoma sụn"],
    ["osteosarcoma", "Sarcoma xương"],
    ["angiosarcoma", "Sarcoma mạch"],
    ["fibrosarcoma", "Sarcoma xơ"],
    ["sarcoma", "Sarcoma"],
    ["adenofibroma", "U tuyến-xơ"],
    ["fibromyxoma", "U xơ-nhầy"],
    ["angiomyxoma", "U mạch-nhầy"],
    ["myxoma", "U nhầy"],
    ["oncocytoma", "U tế bào ưa acid"],
    ["mesothelioma", "U trung biểu mô"],
    ["neuroblastoma", "U nguyên bào thần kinh"],
    ["medulloblastoma", "U nguyên bào tủy"],
    ["pineoblastoma", "U nguyên bào tuyến tùng"],
    ["blastoma", "U nguyên bào"],
    ["neurocytoma", "U tế bào thần kinh"],
    ["ganglioglioma", "U hạch-thần kinh đệm"],
    ["gangliocytoma", "U tế bào hạch"],
    ["haemangioblastoma", "U nguyên bào mạch"],
    ["hemangioblastoma", "U nguyên bào mạch"],
    ["haemangioendothelioma", "U nội mô mạch"],
    ["hemangioendothelioma", "U nội mô mạch"],
    ["angioma", "U mạch"],
    ["neuroma", "U thần kinh"],
    ["osteoma", "U xương"],
    ["osteoblastoma", "U nguyên bào xương"],
    ["chondroma", "U sụn"],
    ["cystadenoma", "U tuyến nang"],
    ["adenoma", "U tuyến"],
    ["papilloma", "U nhú"],
    ["naevus", "Nơvi"],
    ["nevus", "Nơvi"],
    ["melanocytoma", "U tế bào hắc tố"],
    ["keratosis", "Dày sừng"],
    ["melanosis", "Nhiễm hắc tố"],
    ["choristoma", "U lạc chỗ"],
    ["malformation", "Dị dạng"],
    ["lipomatosis", "Bệnh u mỡ"],
    ["leiomyomatosis", "Bệnh đa u cơ trơn"],
    ["schwannomatosis", "Bệnh đa u bao Schwann"],
    ["mastocytosis", "Bệnh tăng sinh dưỡng bào"],
    ["melanoma", "U hắc tố ác tính"],
    ["meningioma", "U màng não"],
    ["glioblastoma", "U nguyên bào thần kinh đệm"],
    ["ependymoma", "U màng não thất"],
    ["astrocytoma", "U tế bào hình sao"],
    ["glioma", "U thần kinh đệm"],
    ["schwannoma", "U bao Schwann"],
    ["neurofibroma", "U xơ thần kinh"],
    ["paraganglioma", "U cận hạch"],
    ["haemangioma", "U máu"],
    ["hemangioma", "U máu"],
    ["fibroma", "U xơ"],
    ["lipoma", "U mỡ"],
    ["leiomyoma", "U cơ trơn"],
    ["hamartoma", "U mô thừa"],
    ["teratoma", "U quái"],
    ["neoplasm", "Tân sinh"],
    ["neoplasia", "Tân sinh"],
    ["hyperplasia", "Quá sản"],
    ["dysplasia", "Loạn sản"],
    ["polyposis", "Bệnh đa polyp"],
    ["papillomatosis", "Bệnh đa u nhú"],
    ["histiocytosis", "Bệnh mô bào"],
    ["syndrome", "Hội chứng"],
    ["disease", "Bệnh"],
    ["tumours", "Các u"],
    ["tumors", "Các u"],
    ["tumour", "U"],
    ["tumor", "U"],
    ["cyst", "Nang"],
    ["polyp", "Polyp"]
  ];

  const tidy = (value) => String(value || "")
    .replace(/\s+/g, " ")
    .replace(/\s+([,;:)])/g, "$1")
    .replace(/([(])\s+/g, "$1")
    .replace(/\s+-\s+/g, "-")
    .replace(/^\s*[,;:-]+\s*/, "")
    .replace(/\s*[,;:-]+\s*$/, "")
    .trim();

  const key = (value) => tidy(value).toLowerCase();
  const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const phraseRegex = (value, flags = "i") => new RegExp(`(^|[^A-Za-z0-9])(${escapeRegExp(value)})(?=$|[^A-Za-z0-9])`, flags);

  function replacePhrase(value, source, target) {
    return value.replace(phraseRegex(source, "gi"), (match, prefix) => `${prefix}${target}`);
  }

  function replaceAllPhrases(value, dictionary) {
    let output = value;
    let lower = output.toLowerCase();
    dictionary.forEach(([source, target]) => {
      if (!lower.includes(source)) return;
      output = replacePhrase(output, source, target);
      lower = output.toLowerCase();
    });
    return tidy(output);
  }

  function extractSites(value) {
    let remainder = value;
    let lower = remainder.toLowerCase();
    const found = [];
    sites.forEach(([source, target]) => {
      if (!lower.includes(source)) return;
      const regex = phraseRegex(source);
      if (!regex.test(remainder)) return;
      remainder = remainder.replace(regex, (match, prefix) => prefix);
      lower = remainder.toLowerCase();
      if (!found.includes(target)) found.push(target);
    });
    remainder = remainder
      .replace(/\b(of the|arising in|of|in|from)\b/gi, " ")
      .replace(/\s+/g, " ");
    return { remainder: tidy(remainder), sites: found };
  }

  function translateWithHead(value) {
    const lower = value.toLowerCase();
    for (const [source, target] of heads) {
      if (!lower.includes(source)) continue;
      const regex = phraseRegex(source);
      const match = regex.exec(value);
      if (!match) continue;
      const headStart = match.index + match[1].length;
      const headEnd = headStart + match[2].length;
      const before = value.slice(0, headStart);
      const after = value.slice(headEnd);
      const extracted = extractSites(`${before} ${after}`);
      const descriptors = replaceAllPhrases(extracted.remainder, phrases);
      const siteText = extracted.sites.join(" và ");
      if (source === "syndrome" || source === "disease") {
        return tidy([target, descriptors, siteText].filter(Boolean).join(" "));
      }
      if (!["carcinoma", "adenocarcinoma", "squamous cell carcinoma", "basal cell carcinoma", "neuroendocrine carcinoma", "renal cell carcinoma", "hepatocellular carcinoma", "urothelial carcinoma", "adenoid cystic carcinoma", "mucoepidermoid carcinoma", "adenosquamous carcinoma"].includes(source)) {
        return tidy([target, descriptors, siteText].filter(Boolean).join(" "));
      }
      return tidy([target, siteText, descriptors].filter(Boolean).join(" "));
    }
    return "";
  }

  const translationCache = new Map();

  function translate(value) {
    const original = tidy(value);
    if (!original) return "";
    if (translationCache.has(original)) return translationCache.get(original);
    const exactMatch = exact[key(original)];
    if (exactMatch) {
      translationCache.set(original, exactMatch);
      return exactMatch;
    }
    const headed = translateWithHead(original);
    if (headed) {
      translationCache.set(original, headed);
      return headed;
    }
    const sitePass = replaceAllPhrases(original, sites);
    const translated = replaceAllPhrases(sitePass, phrases);
    const result = translated || original;
    translationCache.set(original, result);
    return result;
  }

  function translateTrail(values) {
    return (values || []).map(translate).filter(Boolean);
  }

  window.MEDICAL_VI = {
    translate,
    translateTrail,
    sourceNote: "Tên tiếng Anh WHO/WebPathology được giữ nguyên làm danh pháp nguồn; bản dịch tiếng Việt dùng để hỗ trợ tra cứu và học tập.",
  };
}());
